[package]
name = "mayrelsuarezgomez/factura-tcp"
version = "1.0.3"
description = "Sistema de facturación para TCP Cuba"
repository = "https://github.com/asielperezlugo89/facturador-tcp"
readme = "README.md"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/app" = "."

[[command]]
name = "factura-tcp"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = [
    "-m",
    "flask",
    "--app",
    "/app/main",
    "run",
    "--host=0.0.0.0",
    "--port=8080",
    "--no-reload",
]
env = ["PYTHONEXECUTABLE=/bin/python", "PYTHONUNBUFFERED=1"]
